---
# tasks file
# https://docs.openstack.org/install-guide/openstack-services.html
# https://docs.openstack.org/horizon/train/install/install-rdo.html
# https://docs.openstack.org/train/install/

  - include_vars: "{{ playbook_dir }}/config.yml"
  - include_vars: "{{ playbook_dir }}/passwords.yml"
  - include_vars: "main.yml"

  - name: Installing the packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:        
        - openstack-dashboard
  
  - name: Edit the /etc/openstack-dashboard/local_settings.py
    template:
      src: local_settings.j2
      dest: /etc/openstack-dashboard/local_settings.py
      owner: root 
      group: horizon
      mode: '0640'
  
  - name: Add the following line to /etc/apache2/conf-available/openstack-dashboard.conf  if not included
    template:
      src: openstack-dashboard.conf.j2
      dest:  /etc/apache2/conf-available/openstack-dashboard.conf 
      owner: root 
      group: root
      mode: '0644'        

  - name: Restart the web server and session storage service
    systemd:
      state: restarted
      name: "{{ item }}"
    with_items:
      - apache2.service
      - memcached.service


    
      
      




    


