---
# tasks file
# https://docs.openstack.org/install-guide/openstack-services.html
# https://docs.openstack.org/placement/train/install/from-pypi.html
# https://docs.openstack.org/train/install/

  - include_vars: "{{ playbook_dir }}/config.yml"
  - include_vars: "{{ playbook_dir }}/passwords.yml"
  - include_vars: "main.yml"

  - name: Create database and user
    shell: |
      mysql -u root -p{{ ROOT_DBPASS }} -e "DROP DATABASE placement;"
      mysql -u root -p{{ ROOT_DBPASS }} -e "CREATE DATABASE placement;"
      mysql -u root -p{{ ROOT_DBPASS }} -e "GRANT ALL PRIVILEGES ON placement.* TO 'placement'@'localhost' IDENTIFIED BY '{{ PLACEMENT_DBPASS }}';"
      mysql -u root -p{{ ROOT_DBPASS }} -e "GRANT ALL PRIVILEGES ON placement.* TO 'placement'@'%' IDENTIFIED BY '{{ PLACEMENT_DBPASS }}';"


  - name: Create user
    shell: |
      source /root/admin-openrc
      openstack user create --domain default --password {{ PLACEMENT_PASS }} placement     
    args:
      executable: /bin/bash
    
  - name: Add the Placement user to the service project with the admin role
    shell: |
      source /root/admin-openrc
      openstack role add --project service --user placement admin
    args:
      executable: /bin/bash

  - name: Create the Placement API entry in the service catalog
    shell: |
      source /root/admin-openrc
      openstack service create --name placement --description "Placement API" placement
    args:
      executable: /bin/bash
  
  - name: Create the Placement API service endpoints
    shell: |
      source /root/admin-openrc
      openstack endpoint create --region RegionOne placement public http://{{ openstack.controller.name }}:8778
      openstack endpoint create --region RegionOne placement internal http://{{ openstack.controller.name }}:8778
      openstack endpoint create --region RegionOne placement admin http://{{ openstack.controller.name }}:8778
    args:
      executable: /bin/bash

  - name: Uninstalling the packages
    apt:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
        - placement-api


  - name: Installing the packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - placement-api
  
  - name: Edit the /etc/placement/placement.conf 
    template:
      src: placement.conf.j2
      dest: /etc/placement/placement.conf 
      owner: root 
      group: placement
      mode: '0640'
  
  - name: Populate the placement database
    shell: |
      su -s /bin/sh -c "placement-manage db sync" placement
    args:
      warn: no

  - name: Restart the apache2 service
    systemd:
      name: apache2
      enabled: yes
      state: restarted






    


